# Data loader parameters
task_name: "imputation"
train_batch_size : 64 
val_batch_size: 256 
shuffle: True
num_workers: 5
pin_memory: True
scale : True 
train_ratio : 0.7
val_ratio : 0.1
test_ratio : 0.2
random_seed : 13
upsampling_pad_direction : "backward"
upsampling_type : "pad" # pad by default
downsampling_type : "interpolate"
pad_mode : "edge" # constant by default
pad_constant_values : null

# Data parameters
output_type: 'multivariate' # 'multivariate' 

# Experiment parameters
use_amp: False
pct_start: 0.3
max_epoch: 10
anomaly_criterion: 'mse'
lr_scheduler_type: 'onecyclelr' 
finetuning_mode: "end-to-end" # "end-to-end"
debug: False
init_lr: 0.0001 # 1e-4
loss_type: "mse"
log_interval: 1000
checkpoint_interval: 8000

# Model parameters
model_name: "TimesNet"
seq_len: 512
# Partly based on https://github.com/thuml/Time-Series-Library/blob/main/scripts/anomaly_detection/SWAT/TimesNet.sh
d_model: 64 # 16
d_ff: 64 # 16
e_layers: 3
d_layers: 1
top_k: 3 
num_kernels: 6
forecast_horizon: 0