# Data loader parameters
task_name: "classification"
batch_size: 512
shuffle: False
num_workers: 5
pin_memory: True
scale : True
train_ratio : 0.6
val_ratio : 0.1
test_ratio : 0.3
random_seed : 13
upsampling_pad_direction : "backward"
upsampling_type : "pad" # "pad"
downsampling_type : "interpolate"
pad_mode : "edge" # constant by default
pad_constant_values : null

# Experiment parameters
pretraining_run_name: "fearless-planet-52" # "fast-pyramid-63"
pretraining_opt_steps: null
dimension_reduction_method: 'none'
dimension_reduction_components: null
enable_batchwise_pbar: False

# Model parameters
model_name: "MOMENT"
seq_len: 512
patch_len: 8
patch_stride_len: 8
transformer_backbone: 'google/flan-t5-large' # 'google/flan-t5-base' 'google/flan-t5-large'
add_positional_embedding: True
set_input_mask: True # True by default 